FEATURES = ['OUTCOME', 'WEIGHTCLASS', 'METHOD', 'ROUND', 'TIME', 'REFEREE',
       'LOCATION', 'fighter1_sig_strikes_landed',
       'fighter1_sig_strikes_attempted', 'fighter1_sig_strikes_pct',
       'fighter1_total_strikes_landed', 'fighter1_total_strikes_attempted',
       'fighter1_takedowns_landed', 'fighter1_takedowns_attempted',
       'fighter1_takedown_pct', 'fighter1_control_time_sec',
       'fighter1_head_landed', 'fighter1_body_landed', 'fighter1_leg_landed',
       'fighter1_distance_landed', 'fighter1_clinch_landed',
       'fighter1_ground_landed', 'fighter1_KD', 'fighter1_SUB.ATT',
       'fighter1_REV.', 'fighter2_sig_strikes_landed',
       'fighter2_sig_strikes_attempted', 'fighter2_sig_strikes_pct',
       'fighter2_total_strikes_landed', 'fighter2_total_strikes_attempted',
       'fighter2_takedowns_landed', 'fighter2_takedowns_attempted',
       'fighter2_takedown_pct', 'fighter2_control_time_sec',
       'fighter2_head_landed', 'fighter2_body_landed', 'fighter2_leg_landed',
       'fighter2_distance_landed', 'fighter2_clinch_landed',
       'fighter2_ground_landed', 'fighter2_KD', 'fighter2_SUB.ATT',
       'fighter2_REV.', 'fighter1_height', 'fighter1_weight', 'fighter1_reach',
       'fighter1_stance', 'fighter2_height', 'fighter2_weight',
       'fighter2_reach', 'fighter2_stance', 'month',
       'fighter1_age', 'fighter2_age', 'is_title_fight', 'stance_matchup',
       'height_diff', 'weight_diff', 'reach_diff', 'age_diff',
       'fighter1_days_since_last_fight', 'fighter2_days_since_last_fight',
       'fighter1_total_fights', 'fighter2_total_fights',
       'fighter1_days_in_ufc', 'fighter2_days_in_ufc',
       'fighter1_win_rate_last_5', 'fighter2_win_rate_last_5',
       'fighter1_avg_sig_strikes_last_3', 'fighter2_avg_sig_strikes_last_3',
       'fighter1_avg_control_time_last_3', 'fighter2_avg_control_time_last_3']

# Columns to drop after feature engineering
COLS_TO_DROP = ['URL', 'EVENT', 'BOUT', 'DETAILS', 'fighter1_name', 'fighter2_name', 
                'TIME FORMAT', 'fighter1_dob', 'fighter2_dob', 'fighter1_won',
                'fighter1_won_shifted', 'fighter2_won', 'fighter2_won_shifted', 'LOCATION',
                'OUTCOME', 'fighter1_stance', 'fighter2_stance',
                'METHOD', 'ROUND', 'TIME', 'ROUND_numeric', 'TIME_seconds',
                'fighter1_win_method', 'fighter2_win_method',
                'fighter1_win_round', 'fighter2_win_round',
                'fighter1_win_time_sec', 'fighter2_win_time_sec',
                'fighter1_win_finish', 'fighter2_win_finish',
                'fighter1_win_ko', 'fighter2_win_ko',
                'fighter1_win_sub', 'fighter2_win_sub',
                'fighter1_win_decision', 'fighter2_win_decision',
                'fighter1_win_early', 'fighter2_win_early',
                'fighter1_win_finish_shifted', 'fighter2_win_finish_shifted',
                'fighter1_win_ko_shifted', 'fighter2_win_ko_shifted',
                'fighter1_win_sub_shifted', 'fighter2_win_sub_shifted',
                'fighter1_win_decision_shifted', 'fighter2_win_decision_shifted',
                'fighter1_win_round_shifted', 'fighter2_win_round_shifted',
                'fighter1_win_early_shifted', 'fighter2_win_early_shifted',
                'fighter1_win_time_sec_shifted', 'fighter2_win_time_sec_shifted',
                # Intermediate columns for interaction features
                'fighter1_height_filled', 'fighter2_height_filled',
                'fighter1_weight_filled', 'fighter2_weight_filled',
                'fighter1_reach_filled', 'fighter2_reach_filled',
                # Current fight statistics (to be replaced by historical features)
                'fighter1_sig_strikes_landed', 'fighter1_sig_strikes_attempted', 'fighter1_sig_strikes_pct',
                'fighter1_total_strikes_landed', 'fighter1_total_strikes_attempted',
                'fighter1_takedowns_landed', 'fighter1_takedowns_attempted', 'fighter1_takedown_pct',
                'fighter1_control_time_sec', 'fighter1_head_landed', 'fighter1_body_landed',
                'fighter1_leg_landed', 'fighter1_distance_landed', 'fighter1_clinch_landed',
                'fighter1_ground_landed', 'fighter1_KD', 'fighter1_SUB.ATT', 'fighter1_REV.',
                'fighter2_sig_strikes_landed', 'fighter2_sig_strikes_attempted', 'fighter2_sig_strikes_pct',
                'fighter2_total_strikes_landed', 'fighter2_total_strikes_attempted',
                'fighter2_takedowns_landed', 'fighter2_takedowns_attempted', 'fighter2_takedown_pct',
                'fighter2_control_time_sec', 'fighter2_head_landed', 'fighter2_body_landed',
                'fighter2_leg_landed', 'fighter2_distance_landed', 'fighter2_clinch_landed',
                'fighter2_ground_landed', 'fighter2_KD', 'fighter2_SUB.ATT', 'fighter2_REV.']

# Rate columns to fill with 0.0 for NaN values
RATE_COLS = ['fighter1_finish_rate_last_5', 'fighter2_finish_rate_last_5',
             'fighter1_ko_rate_last_5', 'fighter2_ko_rate_last_5',
             'fighter1_sub_rate_last_5', 'fighter2_sub_rate_last_5',
             'fighter1_decision_rate_last_5', 'fighter2_decision_rate_last_5',
             'fighter1_early_finish_rate_last_5', 'fighter2_early_finish_rate_last_5']

# Average columns to fill with median for NaN values
AVG_COLS = ['fighter1_avg_finish_round_last_5', 'fighter2_avg_finish_round_last_5',
            'fighter1_avg_finish_time_last_5', 'fighter2_avg_finish_time_last_5']

# Engineered features we create
ENGINEERED_FEATURES = [
    'month',
    'fighter1_age', 'fighter2_age', 'fighter1_age_unknown', 'fighter2_age_unknown',
    'is_title_fight', 'stance_matchup',
    'height_diff', 'weight_diff', 'reach_diff', 'age_diff', 'age_diff_unknown',
    'fighter1_days_since_last_fight', 'fighter2_days_since_last_fight',
    'fighter1_total_fights', 'fighter2_total_fights',
    'fighter1_days_in_ufc', 'fighter2_days_in_ufc',
    'fighter1_win_rate_last_5', 'fighter2_win_rate_last_5',
    'fighter1_avg_sig_strikes_last_3', 'fighter2_avg_sig_strikes_last_3',
    'fighter1_avg_control_time_last_3', 'fighter2_avg_control_time_last_3',
    'fighter1_avg_total_strikes_landed_last_3', 'fighter2_avg_total_strikes_landed_last_3',
    'fighter1_avg_ground_landed_last_3', 'fighter2_avg_ground_landed_last_3',
    'fighter1_avg_KD_last_3', 'fighter2_avg_KD_last_3',
    'fighter1_avg_head_landed_last_3', 'fighter2_avg_head_landed_last_3',
    'fighter1_avg_body_landed_last_3', 'fighter2_avg_body_landed_last_3',
    'fighter1_avg_leg_landed_last_3', 'fighter2_avg_leg_landed_last_3',
    'fighter1_avg_distance_landed_last_3', 'fighter2_avg_distance_landed_last_3',
    'fighter1_avg_clinch_landed_last_3', 'fighter2_avg_clinch_landed_last_3',
    'fighter1_avg_takedowns_landed_last_3', 'fighter2_avg_takedowns_landed_last_3',
    'fighter1_avg_SUB.ATT_last_3', 'fighter2_avg_SUB.ATT_last_3',
    'fighter1_avg_REV._last_3', 'fighter2_avg_REV._last_3',
    'fighter1_finish_rate_last_5', 'fighter2_finish_rate_last_5',
    'fighter1_ko_rate_last_5', 'fighter2_ko_rate_last_5',
    'fighter1_sub_rate_last_5', 'fighter2_sub_rate_last_5',
    'fighter1_decision_rate_last_5', 'fighter2_decision_rate_last_5',
    'fighter1_avg_finish_round_last_5', 'fighter2_avg_finish_round_last_5',
    'fighter1_early_finish_rate_last_5', 'fighter2_early_finish_rate_last_5',
    'fighter1_avg_finish_time_last_5', 'fighter2_avg_finish_time_last_5',
    # Historical ratio features
    'win_rate_ratio', 'finish_rate_ratio', 'ko_rate_ratio', 'sub_rate_ratio',
    'decision_rate_ratio', 'early_finish_rate_ratio', 'avg_sig_strikes_ratio',
    'avg_control_time_ratio', 'total_fights_ratio', 'days_in_ufc_ratio',
    'avg_finish_round_ratio', 'avg_finish_time_ratio', 'avg_takedowns_ratio',
    'avg_KD_ratio', 'avg_head_strikes_ratio', 'avg_body_strikes_ratio',
    'avg_leg_strikes_ratio', 'avg_distance_strikes_ratio', 'avg_clinch_strikes_ratio',
    'avg_ground_strikes_ratio', 'avg_sub_att_ratio', 'avg_rev_ratio',
    'avg_total_strikes_ratio',
    # Momentum features
    'fighter1_career_win_rate', 'fighter2_career_win_rate',
    'fighter1_momentum', 'fighter2_momentum', 'momentum_diff',
    # Win/loss streak features
    'fighter1_win_streak', 'fighter2_win_streak',
    'fighter1_loss_streak', 'fighter2_loss_streak',
    'win_streak_diff', 'loss_streak_diff',
    # Interaction features
    'reach_advantage_x_striking', 'age_x_experience_diff',
    'size_advantage_f1', 'size_advantage_f2', 'size_advantage_diff',
    'power_advantage_f1', 'power_advantage_f2', 'power_advantage_diff',
    'reach_x_win_rate', 'age_x_momentum', 'size_x_finish_rate',
    # Consistency features
    'fighter1_win_rate_std', 'fighter2_win_rate_std', 'win_rate_consistency_diff',
    'fighter1_strike_output_std', 'fighter2_strike_output_std', 'strike_output_consistency_diff',
    'fighter1_finish_consistency', 'fighter2_finish_consistency', 'finish_consistency_diff',
    'fighter1_control_time_std', 'fighter2_control_time_std', 'control_time_consistency_diff',
    'fighter1_takedown_std', 'fighter2_takedown_std', 'takedown_consistency_diff'
]
